// <auto-generated />
namespace _200396815_A1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Genres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Genres));
        
        string IMigrationMetadata.Id
        {
            get { return "201906122329437_Genres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
